services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: red-acre-app-api
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5000:5000"
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: red-acre-frontend
    ports:
      - "3000:80"